# Generated by Django 3.2.1 on 2021-06-08 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Tweet',
        ),
    ]
