# Generated by Django 3.2.1 on 2021-06-08 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_rename_post_tweet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tweet',
            new_name='Tweetclone',
        ),
        migrations.AlterModelTable(
            name='tweetclone',
            table='tweetclone',
        ),
    ]
