# Generated by Django 3.2.1 on 2021-06-10 04:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20210607_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetclone',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
