# Generated by Django 3.2.1 on 2021-06-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_alter_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetclone',
            name='like_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='LikeCount'),
        ),
    ]
